[E 190119 14:26:22 KumNewServices:37] Error on create method of SysRolePrivilegeService
    Traceback (most recent call last):
      File "D:\pro\kump\modules\services\KumNewServices.py", line 20, in create
        objdb = KumNews()
      File "<string>", line 2, in __init__
      File "C:\Users\jeriy\.virtualenvs\kump\lib\site-packages\sqlalchemy\orm\instrumentation.py", line 408, in _new_state_if_none
        state = self._state_constructor(instance, self)
      File "C:\Users\jeriy\.virtualenvs\kump\lib\site-packages\sqlalchemy\util\langhelpers.py", line 839, in __get__
        obj.__dict__[self.__name__] = result = self.fget(obj)
      File "C:\Users\jeriy\.virtualenvs\kump\lib\site-packages\sqlalchemy\orm\instrumentation.py", line 234, in _state_constructor
        self.dispatch.first_init(self, self.class_)
      File "C:\Users\jeriy\.virtualenvs\kump\lib\site-packages\sqlalchemy\event\attr.py", line 297, in __call__
        fn(*args, **kw)
      File "C:\Users\jeriy\.virtualenvs\kump\lib\site-packages\sqlalchemy\orm\mapper.py", line 3316, in _event_on_first_init
        configure_mappers()
      File "C:\Users\jeriy\.virtualenvs\kump\lib\site-packages\sqlalchemy\orm\mapper.py", line 3201, in configure_mappers
        raise e
    sqlalchemy.exc.InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper|KumNews|kum_news'. Original exception was: Could not determine join condition between parent/child tables on relationship KumNews.topics - there are no foreign keys linking these tables via secondary table 'kum_news_topics'.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify 'primaryjoin' and 'secondaryjoin' expressions.
